import { StudentLearningProfile } from "@/types/learning";

export const MOCK_LEARNING_PROFILES: StudentLearningProfile[] = [
  {
    studentId: 29248,
    nombres: "Benjamín",
    apellidos: "Morales Pizarro",
    rut: "20.481.932-8",
    email: "benjamin.morales3@mail.udp.cl",
    seccionId: "sec_1",
    progresoGeneral: 95,
    nivelRendimiento: "destacado",
    promedioActual: 6.8,
    asistenciaPct: 100,
    reflexionEstudiante: {
      fecha: "05/10/2026",
      texto: "He consolidado la comprensión de Clean Architecture y la integración continua. Siento que el mayor desafío ha sido coordinar el despliegue multi-ambiente, pero logré estructurar la pipeline con pruebas automatizadas robustas.",
      autoevaluacionComprension: 5,
      dificultadesPercibidas: ["Complejidad de pipelines CI/CD avanzadas", "Optimización de consultas SQL en carga"],
      metasProximoHito: "Implementar observabilidad y métricas con Grafana en la Solemne 2.",
    },
    fortalezas: [
      "Diseño arquitectural desacoplado",
      "Liderazgo técnico en equipo",
      "Alta rigurosidad en entrega y documentación",
      "Capacidad de resolución autónoma",
    ],
    debilidades: [
      "Tendencia al sobre-diseño temprano (YAGNI)",
      "Delegación equitativa de tareas de backend",
    ],
    diagnosticoIA: {
      resumen: "Perfil de excelencia técnica y alta autonomía. Evidencia metacognición madura en sus entregables y capacidad para sintetizar problemas complejos.",
      patronAprendizaje: "Aprendizaje inductivo-práctico orientado a la investigación profunda y prototipado rápido.",
      recomendacionDocente: "Asignarle roles de mentoría cruzada dentro de su equipo y desafiarlo con requerimientos no funcionales de alta concurrencia.",
      preguntasGatilladoras: [
        "¿Cómo medirías el impacto de la latencia en tu arquitectura si duplicaras los usuarios simultáneos?",
        "¿De qué forma podrías simplificar la capa de infraestructura sin perder trazabilidad?",
      ],
      accionesSugeridas: [
        "Felicitar desempeño en retroalimentación formativa.",
        "Proponerle liderar la sesión de revisión de código en ayudantía.",
      ],
    },
  },
  {
    studentId: 31021,
    nombres: "Víctor Vicente",
    apellidos: "Barrera Jorquera",
    rut: "21.109.845-K",
    email: "victor.barrera@mail.udp.cl",
    seccionId: "sec_1",
    progresoGeneral: 82,
    nivelRendimiento: "favorable",
    promedioActual: 5.9,
    asistenciaPct: 92,
    reflexionEstudiante: {
      fecha: "03/10/2026",
      texto: "Entiendo bien la lógica del frontend y la interacción con componentes, pero me costó conectar las APIs REST con validación de esquemas Zod.",
      autoevaluacionComprension: 4,
      dificultadesPercibidas: ["Manejo asíncrono avanzado", "Control de errores de red"],
      metasProximoHito: "Asegurar que todas las peticiones tengan tipado estricto extremo a extremo.",
    },
    fortalezas: [
      "Proactividad y participación constante",
      "Gran habilidad en diseño de interfaces y UX",
      "Compromiso con el trabajo grupal",
    ],
    debilidades: [
      "Inseguridad en depuración de errores del servidor",
      "Falta de tests unitarios sistemáticos",
    ],
    diagnosticoIA: {
      resumen: "Estudiante con trayectoria ascendente. Responde muy bien a la retroalimentación constructiva inmediata y muestra gran motivación.",
      patronAprendizaje: "Aprendizaje visual e interactivo. Requiere ejemplos de código comentados paso a paso para afianzar conceptos abstractos.",
      recomendacionDocente: "Reforzar patrones de manejo de errores en llamadas fetch y guiarlo en debugging asistido con breakpoints.",
      preguntasGatilladoras: [
        "¿Qué ocurre en tu aplicación cuando el servidor responde con un estado 500 inesperado?",
      ],
      accionesSugeridas: [
        "Compartir plantilla de validación defensiva en ayudantía.",
        "Revisar conjuntamente su último commit de integración API.",
      ],
    },
  },
  {
    studentId: 32415,
    nombres: "Laura Francisca",
    apellidos: "Salinas Herrera",
    rut: "20.912.433-4",
    email: "laura.salinas1@mail.udp.cl",
    seccionId: "sec_1",
    progresoGeneral: 78,
    nivelRendimiento: "favorable",
    promedioActual: 5.6,
    asistenciaPct: 88,
    reflexionEstudiante: {
      fecha: "01/10/2026",
      texto: "El ritmo del curso ha sido exigente. He aprendido a formular historias de usuario con criterios SMART, aunque la estimación temporal en sprints sigue siendo difícil.",
      autoevaluacionComprension: 4,
      dificultadesPercibidas: ["Estimación de puntos de historia", "Configuración de entorno Docker"],
      metasProximoHito: "Reducir la dispersión en los tiempos de entrega de tareas del sprint.",
    },
    fortalezas: [
      "Excelente capacidad analítica y orden metodológico",
      "Documentación clara y estructurada",
      "Pensamiento crítico constructivo",
    ],
    debilidades: [
      "Dificultades iniciales con virtualización y Docker",
      "Participación oral tímida en plenarios",
    ],
    diagnosticoIA: {
      resumen: "Buen rendimiento con base metodológica sólida. La principal fricción radica en herramientas operativas de DevOps que frenan su velocidad.",
      patronAprendizaje: "Aprendizaje secuencial-lógico. Valora cronogramas claros y rúbricas transparentes.",
      recomendacionDocente: "Proporcionar cápsula de apoyo en contenedores y asignarle intervenciones breves y guiadas en clase para aumentar confianza.",
      preguntasGatilladoras: [
        "¿Cuáles son las dependencias que retrasan tus entregas en los sprints?",
      ],
      accionesSugeridas: [
        "Revisar configuración de Dockerfile en sesión de consultas.",
      ],
    },
  },
  {
    studentId: 33890,
    nombres: "Francisco",
    apellidos: "Alvarado Vivanco",
    rut: "20.765.231-1",
    email: "francisco.alvarado1@mail.udp.cl",
    seccionId: "sec_1",
    progresoGeneral: 48,
    nivelRendimiento: "en_riesgo",
    promedioActual: 3.8,
    asistenciaPct: 62,
    reflexionEstudiante: {
      fecha: "28/09/2026",
      texto: "Me he sentido abrumado con la carga de asignaturas. Quedé atrasado en el Hito 2 y me cuesta coordinar los horarios con mi grupo porque trabajo en las tardes.",
      autoevaluacionComprension: 2,
      dificultadesPercibidas: ["Manejo del tiempo y compatibilidad laboral", "Comprensión de patrones de concurrencia"],
      metasProximoHito: "Poner al día las entregas pendientes y asistir a la ayudantía obligatoria.",
    },
    fortalezas: [
      "Honestidad y transparencia para comunicar dificultades",
      "Creatividad en soluciones conceptuales",
    ],
    debilidades: [
      "Baja asistencia acumulada (62%)",
      "Entrega tardía de evaluaciones formativas",
      "Desconexión de las reuniones de sincronización grupal",
    ],
    diagnosticoIA: {
      resumen: "ALERTA PEDAGÓGICA: Alto riesgo de deserción o reprobación si no se interviene. La causa raíz es sobrecarga externa combinada con brechas en prerrequisitos.",
      patronAprendizaje: "Necesita micro-objetivos semanales con acompañamiento cercano para evitar la procrastinación por sobrecarga.",
      recomendacionDocente: "Agendar reunión de tutoría personalizada inmediata (15 min) para acordar plan de rescate académico y derivación a bienestar si procede.",
      preguntasGatilladoras: [
        "¿Qué 2 compromisos concretos podemos fijar para esta semana que te permitan regularizar tu situación?",
      ],
      accionesSugeridas: [
        "Activar plan de acompañamiento tutorial prioritario.",
        "Flexibilizar entregable formativo con fecha límite convenida.",
        "Validar situación laboral con coordinación docente.",
      ],
    },
  },
  {
    studentId: 34112,
    nombres: "Camila Ignacia",
    apellidos: "Tapia González",
    rut: "21.345.678-9",
    email: "camila.tapia@mail.udp.cl",
    seccionId: "sec_1",
    progresoGeneral: 68,
    nivelRendimiento: "atencion",
    promedioActual: 4.8,
    asistenciaPct: 78,
    reflexionEstudiante: {
      fecha: "02/10/2026",
      texto: "Siento que entiendo la teoría cuando el profesor la explica, pero al momento de escribir código desde cero me bloqueo y dependo mucho de mis compañeros.",
      autoevaluacionComprension: 3,
      dificultadesPercibidas: ["Traducción de requerimientos a código ejecutable", "Uso de Git en ramas compartidas"],
      metasProximoHito: "Completar al menos 3 ejercicios prácticos de ayudantía de forma individual.",
    },
    fortalezas: [
      "Excelente capacidad de comunicación y redacción",
      "Buena síntesis en exposiciones",
    ],
    debilidades: [
      "Baja confianza en destrezas de programación individual",
      "Conflictos recurrentes al resolver merge conflicts en Git",
    ],
    diagnosticoIA: {
      resumen: "Perfil con potencial que requiere superar la barrera de la práctica individual ('síndrome del impostor' en desarrollo práctico).",
      patronAprendizaje: "Aprendizaje por andamiaje (Scaffolding). Se beneficia enormemente de ejercicios guiados con plantillas base.",
      recomendacionDocente: "Asignarle tareas de programación en parejas (pair programming) con un compañero afín y validar sus avances paso a paso.",
      preguntasGatilladoras: [
        "¿Cuál es el primer paso específico que tomas cuando te enfrentas a un problema nuevo de código?",
      ],
      accionesSugeridas: [
        "Monitorear commits individuales en repositorio de proyecto.",
        "Brindarle retroalimentación formativa reforzando sus aciertos.",
      ],
    },
  },
];
